""" add empresa long text

Revision ID: 12bc624fd551
Revises: 35766f8ac42a
Create Date: 2022-03-20 18:04:57.474679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12bc624fd551'
down_revision = '35766f8ac42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
