""" add empresa long text 

Revision ID: 2fbef20a3056
Revises: 626cfa8b6d2a
Create Date: 2022-03-20 18:07:09.151599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbef20a3056'
down_revision = '626cfa8b6d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('filename', sa.Text(length=4294000000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresa', 'filename')
    # ### end Alembic commands ###
