""" add empresa text

Revision ID: 35766f8ac42a
Revises: efc3edb34f1e
Create Date: 2022-03-20 15:46:40.434357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35766f8ac42a'
down_revision = 'efc3edb34f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empresa', 'filename',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empresa', 'filename',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
