""" add empresa long text 

Revision ID: 626cfa8b6d2a
Revises: 12bc624fd551
Create Date: 2022-03-20 18:06:34.476619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '626cfa8b6d2a'
down_revision = '12bc624fd551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresa', 'filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('filename', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
