""" add registro serie

Revision ID: 9f4b59650d49
Revises: 2fbef20a3056
Create Date: 2022-03-22 00:18:41.677888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f4b59650d49'
down_revision = '2fbef20a3056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empresa', 'filename',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294000000),
               existing_nullable=True)
    op.alter_column('imagen_registro', 'file',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294000000),
               existing_nullable=False)
    op.add_column('registro', sa.Column('numero_serie_validador', sa.String(length=100), nullable=True))
    op.add_column('registro', sa.Column('numero_serie_mk', sa.String(length=100), nullable=True))
    op.add_column('registro', sa.Column('numero_serie_teclado', sa.String(length=100), nullable=True))
    op.drop_column('registro', 'numero_serie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registro', sa.Column('numero_serie', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('registro', 'numero_serie_teclado')
    op.drop_column('registro', 'numero_serie_mk')
    op.drop_column('registro', 'numero_serie_validador')
    op.alter_column('imagen_registro', 'file',
               existing_type=sa.Text(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.alter_column('empresa', 'filename',
               existing_type=sa.Text(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
