"""add registro campos

Revision ID: c8c09e9e109a
Revises: c30ad4d48282
Create Date: 2022-03-03 12:42:35.665996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c09e9e109a'
down_revision = 'c30ad4d48282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registro', sa.Column('fecha_editado', sa.DateTime(), nullable=True))
    op.add_column('registro', sa.Column('fecha_eliminado', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registro', 'fecha_eliminado')
    op.drop_column('registro', 'fecha_editado')
    # ### end Alembic commands ###
