""" add empresa fields

Revision ID: efc3edb34f1e
Revises: c8c09e9e109a
Create Date: 2022-03-19 17:25:51.872922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc3edb34f1e'
down_revision = 'c8c09e9e109a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('mail', sa.String(length=200), nullable=False))
    op.add_column('empresa', sa.Column('filename', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresa', 'filename')
    op.drop_column('empresa', 'mail')
    # ### end Alembic commands ###
